using OptiScaler.Core.Models;
using System.Text;
using System.Globalization;

namespace OptiScaler.Core.Services;

/// <summary>
/// Service for reading and writing OptiScaler.ini configuration files
/// </summary>
public class OptiScalerConfigService
{
    /// <summary>
    /// Read OptiScaler configuration from INI file
    /// </summary>
    public OptiScalerConfig ReadConfig(string iniFilePath)
    {
        var config = new OptiScalerConfig();

        if (!File.Exists(iniFilePath))
            return config;

        try
        {
            var lines = File.ReadAllLines(iniFilePath);
            string currentSection = "";

            foreach (var line in lines)
            {
                var trimmedLine = line.Trim();
                
                // Skip comments and empty lines
                if (string.IsNullOrEmpty(trimmedLine) || trimmedLine.StartsWith(";") || trimmedLine.StartsWith("#"))
                    continue;

                // Check for section headers
                if (trimmedLine.StartsWith("[") && trimmedLine.EndsWith("]"))
                {
                    currentSection = trimmedLine[1..^1].ToLowerInvariant();
                    continue;
                }

                // Parse key=value pairs
                if (trimmedLine.Contains("="))
                {
                    var parts = trimmedLine.Split('=', 2);
                    if (parts.Length == 2)
                    {
                        var key = parts[0].Trim().ToLowerInvariant();
                        var value = parts[1].Trim();

                        ParseConfigValue(config, currentSection, key, value);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"Error reading OptiScaler config: {ex.Message}");
        }

        return config;
    }

    /// <summary>
    /// Write OptiScaler configuration to INI file
    /// </summary>
    public void WriteConfig(string iniFilePath, OptiScalerConfig config)
    {
        try
        {
            var sb = new StringBuilder();
            
            // Header
            sb.AppendLine("; OptiScaler Configuration");
            sb.AppendLine("; Generated by OptiScaler Manager");
            sb.AppendLine($"; {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            // [Upscalers] Section
            sb.AppendLine("[Upscalers]");
            sb.AppendLine($"Dx11Upscaler={config.Dx11Upscaler}");
            sb.AppendLine($"Dx12Upscaler={config.Dx12Upscaler}");
            sb.AppendLine($"VulkanUpscaler={config.VulkanUpscaler}");
            sb.AppendLine();

            // [FrameGen] Section
            sb.AppendLine("[FrameGen]");
            sb.AppendLine($"FGType={config.FGType}");
            sb.AppendLine();

            // [OptiFG] Section
            sb.AppendLine("[OptiFG]");
            sb.AppendLine($"Enabled={BoolToString(config.OptiFGEnabled)}");
            sb.AppendLine($"DebugView={BoolToString(config.OptiFGDebugView)}");
            sb.AppendLine($"AllowAsync={BoolToString(config.OptiFGAllowAsync)}");
            sb.AppendLine($"HUDFix={BoolToString(config.OptiFGHUDFix)}");
            sb.AppendLine();

            // [Menu] Section
            sb.AppendLine("[Menu]");
            sb.AppendLine($"OverlayMenu={BoolToString(config.OverlayMenu)}");
            sb.AppendLine($"Scale={config.MenuScale.ToString("F1", CultureInfo.InvariantCulture)}");
            sb.AppendLine($"ShortcutKey={config.ShortcutKey}");
            sb.AppendLine($"ShowFps={BoolToString(config.ShowFps)}");
            sb.AppendLine($"FpsOverlayPos={config.FpsOverlayPos}");
            sb.AppendLine();

            // [DLSS] Section
            sb.AppendLine("[DLSS]");
            sb.AppendLine($"Enabled={BoolToString(config.DLSSEnabled)}");
            if (!string.IsNullOrEmpty(config.DLSSLibraryPath))
                sb.AppendLine($"LibraryPath={config.DLSSLibraryPath}");
            sb.AppendLine($"RenderPresetOverride={BoolToString(config.DLSSRenderPresetOverride)}");
            sb.AppendLine();

            // [FSR] Section
            sb.AppendLine("[FSR]");
            sb.AppendLine($"VerticalFov={config.FSRVerticalFov.ToString("F1", CultureInfo.InvariantCulture)}");
            sb.AppendLine($"CameraNear={config.FSRCameraNear.ToString("F1", CultureInfo.InvariantCulture)}");
            sb.AppendLine($"CameraFar={config.FSRCameraFar.ToString("F1", CultureInfo.InvariantCulture)}");
            sb.AppendLine($"DebugView={BoolToString(config.FSRDebugView)}");
            sb.AppendLine($"UpscalerIndex={config.FSRUpscalerIndex}");
            sb.AppendLine();

            // [XeSS] Section
            sb.AppendLine("[XeSS]");
            sb.AppendLine($"BuildPipelines={BoolToString(config.XeSSBuildPipelines)}");
            sb.AppendLine($"NetworkModel={config.XeSSNetworkModel}");
            if (!string.IsNullOrEmpty(config.XeSSLibraryPath))
                sb.AppendLine($"LibraryPath={config.XeSSLibraryPath}");
            sb.AppendLine();

            // [Spoofing] Section
            sb.AppendLine("[Spoofing]");
            sb.AppendLine($"SpoofedVendorId=0x{config.SpoofedVendorId:X4}");
            sb.AppendLine($"SpoofedDeviceId=0x{config.SpoofedDeviceId:X4}");
            sb.AppendLine($"SpoofedGPUName={config.SpoofedGPUName}");
            sb.AppendLine($"Dxgi={BoolToString(config.DxgiSpoofing)}");
            sb.AppendLine();

            // [QualityOverrides] Section
            sb.AppendLine("[QualityOverrides]");
            sb.AppendLine($"QualityRatioOverrideEnabled={BoolToString(config.QualityRatioOverrideEnabled)}");
            if (config.QualityRatioOverrideEnabled)
            {
                sb.AppendLine($"QualityRatioDLAA={config.QualityRatioDLAA.ToString("F1", CultureInfo.InvariantCulture)}");
                sb.AppendLine($"QualityRatioUltraQuality={config.QualityRatioUltraQuality.ToString("F1", CultureInfo.InvariantCulture)}");
                sb.AppendLine($"QualityRatioQuality={config.QualityRatioQuality.ToString("F1", CultureInfo.InvariantCulture)}");
                sb.AppendLine($"QualityRatioBalanced={config.QualityRatioBalanced.ToString("F1", CultureInfo.InvariantCulture)}");
                sb.AppendLine($"QualityRatioPerformance={config.QualityRatioPerformance.ToString("F1", CultureInfo.InvariantCulture)}");
                sb.AppendLine($"QualityRatioUltraPerformance={config.QualityRatioUltraPerformance.ToString("F1", CultureInfo.InvariantCulture)}");
            }
            sb.AppendLine();

            // [Sharpness] Section
            sb.AppendLine("[Sharpness]");
            sb.AppendLine($"OverrideSharpness={BoolToString(config.SharpnessOverride)}");
            sb.AppendLine($"Sharpness={config.Sharpness.ToString("F1", CultureInfo.InvariantCulture)}");
            sb.AppendLine();

            // [CAS] Section
            sb.AppendLine("[CAS]");
            sb.AppendLine($"Enabled={BoolToString(config.CASEnabled)}");
            sb.AppendLine($"MotionSharpnessEnabled={BoolToString(config.CASMotionSharpnessEnabled)}");
            sb.AppendLine($"MotionSharpness={config.CASMotionSharpness.ToString("F1", CultureInfo.InvariantCulture)}");
            sb.AppendLine();

            // [Log] Section
            sb.AppendLine("[Log]");
            sb.AppendLine($"LogFile={config.LogFile}");
            sb.AppendLine($"LogLevel={config.LogLevel}");
            sb.AppendLine($"LogToFile={BoolToString(config.LogToFile)}");
            sb.AppendLine($"LogToConsole={BoolToString(config.LogToConsole)}");

            File.WriteAllText(iniFilePath, sb.ToString());
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"Error writing OptiScaler config: {ex.Message}");
            throw;
        }
    }

    /// <summary>
    /// Parse individual configuration values
    /// </summary>
    private void ParseConfigValue(OptiScalerConfig config, string section, string key, string value)
    {
        try
        {
            switch (section)
            {
                case "upscalers":
                    switch (key)
                    {
                        case "dx11upscaler": config.Dx11Upscaler = value; break;
                        case "dx12upscaler": config.Dx12Upscaler = value; break;
                        case "vulkanupscaler": config.VulkanUpscaler = value; break;
                    }
                    break;

                case "framegen":
                    switch (key)
                    {
                        case "fgtype": config.FGType = value; break;
                    }
                    break;

                case "optifg":
                    switch (key)
                    {
                        case "enabled": config.OptiFGEnabled = ParseBool(value); break;
                        case "debugview": config.OptiFGDebugView = ParseBool(value); break;
                        case "allowasync": config.OptiFGAllowAsync = ParseBool(value); break;
                        case "hudfix": config.OptiFGHUDFix = ParseBool(value); break;
                    }
                    break;

                case "menu":
                    switch (key)
                    {
                        case "overlaymenu": config.OverlayMenu = ParseBool(value); break;
                        case "scale": config.MenuScale = ParseFloat(value, config.MenuScale); break;
                        case "shortcutkey": config.ShortcutKey = ParseInt(value, config.ShortcutKey); break;
                        case "showfps": config.ShowFps = ParseBool(value); break;
                        case "fpsoverlaypos": config.FpsOverlayPos = ParseInt(value, config.FpsOverlayPos); break;
                    }
                    break;

                case "dlss":
                    switch (key)
                    {
                        case "enabled": config.DLSSEnabled = ParseBool(value); break;
                        case "librarypath": config.DLSSLibraryPath = value; break;
                        case "renderpresetoverride": config.DLSSRenderPresetOverride = ParseBool(value); break;
                    }
                    break;

                case "fsr":
                    switch (key)
                    {
                        case "verticalfov": config.FSRVerticalFov = ParseFloat(value, config.FSRVerticalFov); break;
                        case "cameranear": config.FSRCameraNear = ParseFloat(value, config.FSRCameraNear); break;
                        case "camerafar": config.FSRCameraFar = ParseFloat(value, config.FSRCameraFar); break;
                        case "debugview": config.FSRDebugView = ParseBool(value); break;
                        case "upscalerindex": config.FSRUpscalerIndex = ParseInt(value, config.FSRUpscalerIndex); break;
                    }
                    break;

                case "xess":
                    switch (key)
                    {
                        case "buildpipelines": config.XeSSBuildPipelines = ParseBool(value); break;
                        case "networkmodel": config.XeSSNetworkModel = ParseInt(value, config.XeSSNetworkModel); break;
                        case "librarypath": config.XeSSLibraryPath = value; break;
                    }
                    break;

                case "spoofing":
                    switch (key)
                    {
                        case "spoofedvendorid": config.SpoofedVendorId = ParseHex(value, config.SpoofedVendorId); break;
                        case "spoofeddeviceid": config.SpoofedDeviceId = ParseHex(value, config.SpoofedDeviceId); break;
                        case "spoofedgpuname": config.SpoofedGPUName = value; break;
                        case "dxgi": config.DxgiSpoofing = ParseBool(value); break;
                    }
                    break;

                case "qualityoverrides":
                    switch (key)
                    {
                        case "qualityratiooverrideenabled": config.QualityRatioOverrideEnabled = ParseBool(value); break;
                        case "qualityratiodlaa": config.QualityRatioDLAA = ParseFloat(value, config.QualityRatioDLAA); break;
                        case "qualityratioultrapuality": config.QualityRatioUltraQuality = ParseFloat(value, config.QualityRatioUltraQuality); break;
                        case "qualityratioqualyty": config.QualityRatioQuality = ParseFloat(value, config.QualityRatioQuality); break;
                        case "qualityratiobalanced": config.QualityRatioBalanced = ParseFloat(value, config.QualityRatioBalanced); break;
                        case "qualityratioperfomance": config.QualityRatioPerformance = ParseFloat(value, config.QualityRatioPerformance); break;
                        case "qualityratioultraperformance": config.QualityRatioUltraPerformance = ParseFloat(value, config.QualityRatioUltraPerformance); break;
                    }
                    break;

                case "sharpness":
                    switch (key)
                    {
                        case "overridesharpness": config.SharpnessOverride = ParseBool(value); break;
                        case "sharpness": config.Sharpness = ParseFloat(value, config.Sharpness); break;
                    }
                    break;

                case "cas":
                    switch (key)
                    {
                        case "enabled": config.CASEnabled = ParseBool(value); break;
                        case "motionsharpnessenabled": config.CASMotionSharpnessEnabled = ParseBool(value); break;
                        case "motionsharpness": config.CASMotionSharpness = ParseFloat(value, config.CASMotionSharpness); break;
                    }
                    break;

                case "log":
                    switch (key)
                    {
                        case "logfile": config.LogFile = value; break;
                        case "loglevel": config.LogLevel = ParseInt(value, config.LogLevel); break;
                        case "logtofile": config.LogToFile = ParseBool(value); break;
                        case "logtoconsole": config.LogToConsole = ParseBool(value); break;
                    }
                    break;
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"Error parsing config value {section}.{key}={value}: {ex.Message}");
        }
    }

    /// <summary>
    /// Parse boolean values (handles "auto", "true", "false", "1", "0")
    /// </summary>
    private bool ParseBool(string value)
    {
        if (string.IsNullOrEmpty(value)) return false;
        
        var lowerValue = value.ToLowerInvariant();
        return lowerValue switch
        {
            "true" or "1" or "yes" or "on" or "enabled" => true,
            "auto" => false, // Default for auto is usually false
            _ => false
        };
    }

    /// <summary>
    /// Parse float values with fallback
    /// </summary>
    private float ParseFloat(string value, float defaultValue)
    {
        if (string.IsNullOrEmpty(value) || value.ToLowerInvariant() == "auto")
            return defaultValue;

        return float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out float result) 
            ? result 
            : defaultValue;
    }

    /// <summary>
    /// Parse integer values with fallback
    /// </summary>
    private int ParseInt(string value, int defaultValue)
    {
        if (string.IsNullOrEmpty(value) || value.ToLowerInvariant() == "auto")
            return defaultValue;

        return int.TryParse(value, out int result) ? result : defaultValue;
    }

    /// <summary>
    /// Parse hexadecimal values with fallback
    /// </summary>
    private int ParseHex(string value, int defaultValue)
    {
        if (string.IsNullOrEmpty(value) || value.ToLowerInvariant() == "auto")
            return defaultValue;

        // Remove 0x prefix if present
        if (value.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
            value = value[2..];

        return int.TryParse(value, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out int result) 
            ? result 
            : defaultValue;
    }

    /// <summary>
    /// Convert boolean to string for INI file
    /// </summary>
    private string BoolToString(bool value) => value ? "true" : "false";
}